import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import type { Dirent } from "node:fs";
import { access, readdir, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import { Effect } from "effect";

/**
 * Removes the service runners dir (`<config dir>\service-runners`) on
 * uninstall, including when a runner in it is still running.
 *
 * Windows never deletes the image of a running process, so an uninstall run
 * by the runner exe itself (or while a scheduled sync is still running) could
 * delete everything but that exe. Windows does let a running image be renamed,
 * and with it the dir it sits in, which is how npm moves a running package
 * aside. So on Windows a runners dir that will not go away is renamed to a
 * retired name next to it: the service is fully uninstalled at once, and a
 * later install writes a fresh runners dir. A hidden wscript.exe waits for the
 * exe to exit and deletes the retired dir, and every later install, uninstall
 * and scheduled run sweeps any retired dir that is still there.
 */

const RETIRED_RUNNERS_PREFIX = "service-runners.retired-";
const RETIRED_RUNNERS_NAME = /^service-runners\.retired-[0-9a-f]{8}$/;
const CLEANUP_SCRIPT_EXTENSION = ".vbs";
// How long the cleanup script keeps retrying: a scheduled sync that was
// running during the uninstall can take a few minutes to finish.
const CLEANUP_ATTEMPTS = 300;
const CLEANUP_INTERVAL_MS = 1000;

interface RunnerRemovalFs {
  exists: (path: string) => Promise<boolean>;
  readdir: (path: string) => Promise<Dirent[]>;
  rename: (from: string, to: string) => Promise<void>;
  rm: (path: string) => Promise<void>;
  /** Starts the detached, hidden cleanup script. Never throws. */
  startCleanup: (scriptPath: string) => void;
  writeFile: (path: string, content: string) => Promise<void>;
}

type RunnersRemoval =
  | { readonly _tag: "removed" }
  /** Retired aside because a runner in it is running; deleted once it exits. */
  | { readonly _tag: "retired"; readonly path: string };

const nodeFs: RunnerRemovalFs = {
  exists: async (path) => {
    try {
      await access(path);
      return true;
    } catch {
      return false;
    }
  },
  readdir: (path) => readdir(path, { withFileTypes: true }),
  rename,
  rm: (path) => rm(path, { force: true, recursive: true }),
  startCleanup: (scriptPath) => {
    try {
      // wscript.exe is a GUI program, so the detached script opens no console
      // window, and it needs no console program to wait or delete.
      const child = spawn(
        windowsScriptHostPath(process.env),
        ["//B", "//NoLogo", "//E:VBScript", scriptPath],
        { detached: true, stdio: "ignore", windowsHide: true },
      );
      child.on("error", () => {
        // The next install, uninstall or scheduled run sweeps the retired dir.
      });
      child.unref();
    } catch {
      // As above.
    }
  },
  writeFile: (path, content) => writeFile(path, content),
};

// Task Scheduler runs actions from its native (64-bit on x64/arm64) host, so %SystemRoot%\System32
// is always the native wscript.exe there, even if this CLI runs under WOW64 file-system redirection.
function windowsScriptHostPath(env: Record<string, string | undefined> = process.env): string {
  const systemRoot = env["SystemRoot"] ?? env["SYSTEMROOT"] ?? "C:\\Windows";

  return `${systemRoot.replace(/[\\/]+$/, "")}\\System32\\wscript.exe`;
}

function isRetiredRunnersName(name: string): boolean {
  return RETIRED_RUNNERS_NAME.test(name);
}

function retiredRunnersPath(runnersDir: string, id: string = randomUUID()): string {
  return join(
    dirname(runnersDir),
    `${RETIRED_RUNNERS_PREFIX}${id.replaceAll("-", "").slice(0, 8)}`,
  );
}

/**
 * The cleanup script for a retired dir sits next to it as `<dir>.vbs`, so the
 * path never travels through a command line. It retries until the dir is
 * gone, then deletes itself. Plain ASCII: wscript reads a script without a
 * byte-order mark in the ANSI code page.
 */
function renderRunnerCleanupScript(): string {
  return `' Generated by tokenmaxxing. Deletes a service runner dir that was still running at uninstall.\r
Option Explicit\r
Dim fso, target, attempt\r
Set fso = CreateObject("Scripting.FileSystemObject")\r
target = Left(WScript.ScriptFullName, Len(WScript.ScriptFullName) - ${CLEANUP_SCRIPT_EXTENSION.length})\r
On Error Resume Next\r
For attempt = 1 To ${CLEANUP_ATTEMPTS}\r
  WScript.Sleep ${CLEANUP_INTERVAL_MS}\r
  If fso.FolderExists(target) Then fso.DeleteFolder target, True\r
  Err.Clear\r
  If Not fso.FolderExists(target) Then Exit For\r
Next\r
If Not fso.FolderExists(target) Then fso.DeleteFile WScript.ScriptFullName, True\r
`;
}

/**
 * Deletes the runners dir. On Windows, a dir that keeps a running runner is
 * renamed aside and handed to the cleanup script instead; the rename failing
 * (a process has its working directory in there) fails the removal with the
 * delete's error. Elsewhere a running binary never blocks the delete.
 */
async function removeRunnersDir(
  runnersDir: string,
  platform: NodeJS.Platform,
  fs: RunnerRemovalFs,
): Promise<RunnersRemoval> {
  try {
    await fs.rm(runnersDir);
    return { _tag: "removed" };
  } catch (cause) {
    if (platform !== "win32") {
      throw cause;
    }
    const retired = retiredRunnersPath(runnersDir);
    try {
      await fs.rename(runnersDir, retired);
    } catch {
      throw cause;
    }
    // Everything but the running image goes now.
    await fs.rm(retired).catch(() => {});
    if (!(await fs.exists(retired))) {
      return { _tag: "removed" };
    }
    try {
      const scriptPath = `${retired}${CLEANUP_SCRIPT_EXTENSION}`;
      await fs.writeFile(scriptPath, renderRunnerCleanupScript());
      fs.startCleanup(scriptPath);
    } catch {
      // The next install, uninstall or scheduled run sweeps the retired dir.
    }
    return { _tag: "retired", path: retired };
  }
}

/**
 * Deletes the retired runner dirs in `configDir`, then the cleanup scripts
 * whose dir is gone (their wscript.exe was stopped before it finished). A dir
 * whose runner is still running stays for a later run. Never fails.
 */
async function sweepRetiredRunners(configDir: string, fs: RunnerRemovalFs): Promise<void> {
  const entries = await fs.readdir(configDir).catch(() => []);
  for (const entry of entries) {
    if (entry.isDirectory() && isRetiredRunnersName(entry.name)) {
      await fs.rm(join(configDir, entry.name)).catch(() => {});
    }
  }
  for (const entry of entries) {
    const dirName = entry.name.slice(0, -CLEANUP_SCRIPT_EXTENSION.length);
    if (
      entry.isFile() &&
      entry.name.endsWith(CLEANUP_SCRIPT_EXTENSION) &&
      isRetiredRunnersName(dirName) &&
      !(await fs.exists(join(configDir, dirName)))
    ) {
      await fs.rm(join(configDir, entry.name)).catch(() => {});
    }
  }
}

function removeServiceRunnersDir(
  runnersDir: string,
  platform: NodeJS.Platform = process.platform,
  fs: RunnerRemovalFs = nodeFs,
): Effect.Effect<RunnersRemoval, unknown> {
  return Effect.tryPromise({
    try: () => removeRunnersDir(runnersDir, platform, fs),
    catch: (cause) => cause,
  });
}

function removeRetiredServiceRunners(
  runnersDir: string,
  platform: NodeJS.Platform = process.platform,
  fs: RunnerRemovalFs = nodeFs,
): Effect.Effect<void, never> {
  if (platform !== "win32") {
    return Effect.void;
  }

  return Effect.tryPromise({
    try: () => sweepRetiredRunners(dirname(runnersDir), fs),
    catch: (cause) => cause,
  }).pipe(Effect.ignore);
}

export {
  isRetiredRunnersName,
  removeRetiredServiceRunners,
  removeServiceRunnersDir,
  renderRunnerCleanupScript,
  retiredRunnersPath,
  windowsScriptHostPath,
};
export type { RunnerRemovalFs, RunnersRemoval };
